// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.geoxp.client.widgets.poipanel;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface PoiPanelCssResource extends CssResource {
  
  @ClassName("POIPanel-Root")
  String pOIPanelRoot();
}

